ALTER TABLE `Task` MODIFY `status` ENUM('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'PENDING_REVIEW', 'DONE', 'CANCELLED') NOT NULL DEFAULT 'OPEN';

ALTER TABLE `TaskActivity` MODIFY `fromStatus` ENUM('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'PENDING_REVIEW', 'DONE', 'CANCELLED') NULL;
ALTER TABLE `TaskActivity` MODIFY `toStatus` ENUM('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'PENDING_REVIEW', 'DONE', 'CANCELLED') NULL;

ALTER TABLE `UserNotification` MODIFY `type` ENUM('TASK_ASSIGNED', 'TASK_FOLLOW_UP_DUE', 'TASK_COMMENT', 'TASK_STATUS', 'TASK_SUBMITTED_FOR_REVIEW') NOT NULL;
