/**
 * Canonical IT / ICT product categories for dropdown selection.
 * Stored as VARCHAR(128) on Product.category — keep each label ≤ 128 chars.
 */
export const IT_PRODUCT_CATEGORIES: readonly string[] = [
  "3D printers & consumables",
  "Access control — electronic",
  "Accessories — cables & adapters",
  "Accessories — cleaning kits",
  "Accessories — device cases & bags",
  "Accessories — docking stations",
  "Accessories — hubs & splitters",
  "Accessories — KVM switches",
  "Accessories — locks & security slots",
  "Accessories — mounts & stands",
  "Accessories — privacy filters",
  "Accessories — stylus & pens",
  "Active Directory / LDAP software",
  "AI / machine learning platforms",
  "Antivirus & endpoint protection",
  "Application performance monitoring (APM)",
  "Application servers",
  "Asset management software",
  "Audio — conference phones",
  "Audio — headsets & microphones",
  "Audio — speakers",
  "Backup appliances",
  "Backup media — tapes & cartridges",
  "Backup software",
  "Barcode scanners & readers",
  "BI & analytics software",
  "Blade servers",
  "Boards & components — development kits",
  "Business continuity & DR services",
  "Business intelligence consulting",
  "Cable management & raceway",
  "CAD / CAM software",
  "Cameras — document & overhead",
  "Cameras — IP security",
  "Cameras — webcams",
  "CDN & edge delivery services",
  "Certification & IT training",
  "Chromebooks & education devices",
  "Cloud backup (SaaS)",
  "Cloud compute (IaaS / VMs)",
  "Cloud databases (managed)",
  "Cloud file sync & share",
  "Cloud identity & SSO (IdP)",
  "Cloud monitoring & observability",
  "Cloud networking (VPC, transit)",
  "Cloud office suites",
  "Collaboration & chat platforms",
  "Compliance & GRC software",
  "Conference room AV bundles",
  "Consulting — cloud architecture",
  "Consulting — cybersecurity",
  "Consulting — IT strategy",
  "Consulting — network design",
  "Container & Kubernetes platforms",
  "CRM software",
  "Cybersecurity appliances (UTM / NGFW)",
  "Dark fiber & leased lines",
  "Data center — cages & containment",
  "Data center — design & build",
  "Data center — environmental sensors",
  "Data center — PDUs & power",
  "Data center — raised floor & infrastructure",
  "Data center — remote hands services",
  "Data lakes & warehousing software",
  "Data migration services",
  "Database software",
  "Desktops — all-in-one",
  "Desktops — tower & SFF",
  "DevOps & CI/CD tools",
  "Digital signage players & CMS",
  "Disk enclosures & JBOD",
  "DNS, domains & SSL certificates",
  "Document management / ECM",
  "E-discovery & archiving",
  "E-learning & LMS platforms",
  "Email security gateways",
  "Email servers & gateways",
  "Embedded & IoT gateways",
  "Endpoint detection & response (EDR)",
  "ERP software",
  "Ethernet switches — desktop",
  "Ethernet switches — industrial",
  "Ethernet switches — managed L2/L3",
  "Facilities & DCIM software",
  "Fax servers & ATAs (legacy)",
  "Fiber optics — modules & transceivers",
  "Fiber optics — patch cords & pigtails",
  "Fiber optics — patch panels & enclosures",
  "File servers & NAS",
  "Firewall appliances",
  "GPS & fleet telematics hardware",
  "GPU accelerators & graphics cards",
  "Hard drives — external",
  "Hard drives — internal HDD",
  "Help desk / ITSM software",
  "High-performance computing (HPC)",
  "Hypervisors & virtualization licenses",
  "Identity & access management (IAM)",
  "Industrial PCs & HMIs",
  "Interactive displays & whiteboards",
  "Internet of Things (IoT) sensors",
  "Intrusion detection / prevention (IDS/IPS)",
  "IP phones & softphone licenses",
  "IT documentation & diagramming tools",
  "IT hardware warranty extensions",
  "IT managed services (MSP)",
  "Keyboards",
  "Laptops & notebooks",
  "Load balancers — hardware",
  "Load balancers — software / ADC",
  "Low-code / no-code platforms",
  "Mail archiving appliances",
  "Maintenance — hardware depot",
  "Maintenance — on-site support contracts",
  "Memory (RAM)",
  "Mobile device management (MDM)",
  "Mobile hotspots & cellular routers",
  "Modems & DSL equipment",
  "Monitors — desktop",
  "Monitors — medical / specialty",
  "Monitors — ultrawide & docking",
  "Motherboards & barebones",
  "Multifunction printers (MFP)",
  "Network attached storage (NAS)",
  "Network taps & packet brokers",
  "Networking — media converters",
  "Networking — PoE injectors & midspans",
  "Networking — rack kits & ears",
  "NFC & smart card readers",
  "Office productivity software",
  "Operating systems & CALs",
  "Optical drives (external / internal)",
  "Patch panels & keystone jacks",
  "Patching services & audits",
  "Penetration testing services",
  "Point-of-sale (POS) hardware",
  "Power distribution units (PDU)",
  "Power supplies — external adapters",
  "Power supplies — internal ATX/SFX",
  "Print management software",
  "Printers — label & receipt",
  "Printers — laser & inkjet",
  "Private cloud software",
  "Projectors",
  "Racks — cabinets & open frame",
  "Racks — shelves & drawers",
  "Racks — thermal & fan accessories",
  "Radio & wireless backhaul",
  "Remote access & VPN concentrators",
  "RFID hardware & tags",
  "Routers — branch / SD-WAN",
  "Routers — consumer / SOHO",
  "Routers — enterprise core",
  "SAN & Fibre Channel switches",
  "Scanners — document",
  "Scanners — flatbed / sheet-fed",
  "SD-WAN appliances & licenses",
  "Security cameras — accessories",
  "Security information & event management (SIEM)",
  "Servers — GPU servers",
  "Servers — rack & tower",
  "Single-board computers",
  "Smartboards & collaboration displays",
  "Smartphones & tablets (business)",
  "Software licensing — Adobe & creative",
  "Software licensing — Microsoft",
  "Software licensing — Oracle",
  "Software licensing — VMware / Broadcom",
  "Solid-state drives (SSD)",
  "Storage area network (SAN)",
  "Storage networking — HBAs & CNAs",
  "Structured cabling — copper (Cat5e–Cat8)",
  "Structured cabling — fiber backbone",
  "Structured cabling — installation services",
  "Surge protectors & power strips",
  "Tablets & 2-in-1 devices",
  "Tape libraries & autoloaders",
  "Telephony — PBX & IP-PBX",
  "Test & measurement — network analyzers",
  "Thin clients & zero clients",
  "Time clocks & attendance hardware",
  "Touchpads & trackballs",
  "TPM & hardware security modules (HSM)",
  "UPS — desktop",
  "UPS — rack / line-interactive / online",
  "USB flash drives",
  "Video capture & streaming devices",
  "Video conferencing licenses",
  "Virtual desktop infrastructure (VDI)",
  "VoIP gateways & SBCs",
  "VPN software & clients",
  "WAN optimization appliances",
  "Warranty & support — software",
  "Wearables — business",
  "White-label / OEM components",
  "Wi-Fi access points — indoor",
  "Wi-Fi access points — outdoor",
  "Wi-Fi controllers & cloud management",
  "Wireless site survey services",
  "Workstations — CAD / engineering",
  "Workstations — general",
  "Zoning & HVAC integration (BMS)",
].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));

/** For lookups: allow empty / uncategorized alongside the canonical list. */
export const IT_PRODUCT_CATEGORY_LOOKUP: readonly string[] = ["", ...IT_PRODUCT_CATEGORIES];

/** Built-in IT list + saved API labels + current cell value (deduped, sorted). */
export function mergeProductCategoryChoices(
  savedLabels: readonly string[],
  current?: string | null,
): string[] {
  const s = new Set<string>();
  for (const x of IT_PRODUCT_CATEGORIES) {
    s.add(x);
  }
  for (const x of savedLabels) {
    const t = String(x).trim();
    if (t) {
      s.add(t);
    }
  }
  const c = typeof current === "string" ? current.trim() : "";
  if (c) {
    s.add(c);
  }
  return [...s].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
}

/** SelectBox items: blank row first for “no category”, then merged choices. */
export function productCategorySelectItems(
  savedLabels: readonly string[],
  current?: string | null,
): string[] {
  return ["", ...mergeProductCategoryChoices(savedLabels, current)];
}

/** Filter-row lookup: empty string + all known labels. */
export function productCategoryFilterLookup(savedLabels: readonly string[]): string[] {
  return ["", ...mergeProductCategoryChoices(savedLabels, null)];
}
