export { default as HomePage } from "./home-page";
export { default as UsersPage } from "./users-page";
export { default as CompaniesPage } from "./companies-page";
export { default as SitesPage } from "./sites-page";
export { default as PersonnelPage } from "./personnel-page";
export { default as ProductsPage } from "./products-page";
export { default as StockPage } from "./stock-page";
export { default as PurchasesPage } from "./purchases-page";
export { default as SuppliersPage } from "./suppliers-page";
